FROM continuumio/miniconda3

RUN apt update && apt upgrade -y
RUN apt install -y build-essential
RUN conda create -n simunet
# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "simunet", "/bin/bash", "-c"]    
RUN conda config --append channels conda-forge                                    && \
    conda config --prepend channels https://packages.nnpdf.science/public/         
RUN conda install --only-deps nnpdf=4.0.5
RUN conda install gxx_linux-64
RUN conda install pkg-config swig cmake rhash
RUN conda install sysroot_linux-64=2.17
WORKDIR /simunet_git
COPY . .
WORKDIR /simunet_git/SIMUnet/conda-bld
RUN cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
RUN make
RUN make install
WORKDIR /simunet_git/SIMUnet/n3fit/runcards/examples
RUN vp-setupfit Basic_runcard.yml
